//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2020/1/21 19:22:08
namespace Exercise_form.ServiceReference1
{
    
    /// <summary>
    /// 架构中不存在 db_exerciseEntities 的注释。
    /// </summary>
    public partial class db_exerciseEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 db_exerciseEntities 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public db_exerciseEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "db_exerciseModel", "Exercise_form.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Exercise_form.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("db_exerciseModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 mchoiceQues 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<mchoiceQues> mchoiceQues
        {
            get
            {
                if ((this._mchoiceQues == null))
                {
                    this._mchoiceQues = base.CreateQuery<mchoiceQues>("mchoiceQues");
                }
                return this._mchoiceQues;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<mchoiceQues> _mchoiceQues;
        /// <summary>
        /// 架构中不存在 mchoiceQues 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTomchoiceQues(mchoiceQues mchoiceQues)
        {
            base.AddObject("mchoiceQues", mchoiceQues);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = @"<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edmx""><edmx:DataServices m:DataServiceVersion=""1.0"" m:MaxDataServiceVersion=""3.0"" xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataservices/metadata""><Schema Namespace=""db_exerciseModel"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityType Name=""mchoiceQues""><Key><PropertyRef Name=""id"" /></Key><Property Name=""id"" Type=""Edm.Int32"" Nullable=""false"" p6:StoreGeneratedPattern=""Identity"" xmlns:p6=""http://schemas.microsoft.com/ado/2009/02/edm/annotation"" /><Property Name=""ques"" Type=""Edm.String"" MaxLength=""Max"" FixedLength=""false"" Unicode=""false"" /><Property Name=""answ"" Type=""Edm.Int32"" /><Property Name=""con"" Type=""Edm.Int32"" /><Property Name=""objective"" Type=""Edm.Int32"" /><Property Name=""diff"" Type=""Edm.Int32"" /><Property Name=""usenum"" Type=""Edm.Int32"" /><Property Name=""errornum"" Type=""Edm.Int32"" /><Property Name=""question"" Type=""Edm.Binary"" MaxLength=""Max"" FixedLength=""false"" /></EntityType></Schema><Schema Namespace=""WCFDBservice"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityContainer Name=""db_exerciseEntities"" m:IsDefaultEntityContainer=""true"" p6:LazyLoadingEnabled=""true"" xmlns:p6=""http://schemas.microsoft.com/ado/2009/02/edm/annotation""><EntitySet Name=""mchoiceQues"" EntityType=""db_exerciseModel.mchoiceQues"" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 db_exerciseModel.mchoiceQues 的注释。
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("mchoiceQues")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class mchoiceQues : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 mchoiceQues 对象。
        /// </summary>
        /// <param name="ID">id 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static mchoiceQues CreatemchoiceQues(int ID)
        {
            mchoiceQues mchoiceQues = new mchoiceQues();
            mchoiceQues.id = ID;
            return mchoiceQues;
        }
        /// <summary>
        /// 架构中不存在属性 id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// 架构中不存在属性 ques 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ques
        {
            get
            {
                return this._ques;
            }
            set
            {
                this.OnquesChanging(value);
                this._ques = value;
                this.OnquesChanged();
                this.OnPropertyChanged("ques");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ques;
        partial void OnquesChanging(string value);
        partial void OnquesChanged();
        /// <summary>
        /// 架构中不存在属性 answ 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> answ
        {
            get
            {
                return this._answ;
            }
            set
            {
                this.OnanswChanging(value);
                this._answ = value;
                this.OnanswChanged();
                this.OnPropertyChanged("answ");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _answ;
        partial void OnanswChanging(global::System.Nullable<int> value);
        partial void OnanswChanged();
        /// <summary>
        /// 架构中不存在属性 con 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> con
        {
            get
            {
                return this._con;
            }
            set
            {
                this.OnconChanging(value);
                this._con = value;
                this.OnconChanged();
                this.OnPropertyChanged("con");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _con;
        partial void OnconChanging(global::System.Nullable<int> value);
        partial void OnconChanged();
        /// <summary>
        /// 架构中不存在属性 objective 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> objective
        {
            get
            {
                return this._objective;
            }
            set
            {
                this.OnobjectiveChanging(value);
                this._objective = value;
                this.OnobjectiveChanged();
                this.OnPropertyChanged("objective");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _objective;
        partial void OnobjectiveChanging(global::System.Nullable<int> value);
        partial void OnobjectiveChanged();
        /// <summary>
        /// 架构中不存在属性 diff 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> diff
        {
            get
            {
                return this._diff;
            }
            set
            {
                this.OndiffChanging(value);
                this._diff = value;
                this.OndiffChanged();
                this.OnPropertyChanged("diff");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _diff;
        partial void OndiffChanging(global::System.Nullable<int> value);
        partial void OndiffChanged();
        /// <summary>
        /// 架构中不存在属性 usenum 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> usenum
        {
            get
            {
                return this._usenum;
            }
            set
            {
                this.OnusenumChanging(value);
                this._usenum = value;
                this.OnusenumChanged();
                this.OnPropertyChanged("usenum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _usenum;
        partial void OnusenumChanging(global::System.Nullable<int> value);
        partial void OnusenumChanged();
        /// <summary>
        /// 架构中不存在属性 errornum 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> errornum
        {
            get
            {
                return this._errornum;
            }
            set
            {
                this.OnerrornumChanging(value);
                this._errornum = value;
                this.OnerrornumChanged();
                this.OnPropertyChanged("errornum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _errornum;
        partial void OnerrornumChanging(global::System.Nullable<int> value);
        partial void OnerrornumChanged();
        /// <summary>
        /// 架构中不存在属性 question 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] question
        {
            get
            {
                if ((this._question != null))
                {
                    return ((byte[])(this._question.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnquestionChanging(value);
                this._question = value;
                this.OnquestionChanged();
                this.OnPropertyChanged("question");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _question;
        partial void OnquestionChanging(byte[] value);
        partial void OnquestionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
