//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class classinfo
    {
        public int classid { get; set; }
        public string classinfo1 { get; set; }
        public Nullable<int> courseid { get; set; }
        public string teacher { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<int> finish { get; set; }
    }
}
