//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class classExp
    {
        public int cid { get; set; }
        public int expid { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<bool> attach { get; set; }
        public Nullable<int> dispaly { get; set; }
        public Nullable<int> maxfile { get; set; }
        public Nullable<int> maxatta { get; set; }
    }
}
