//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int id { get; set; }
        public string CourseName { get; set; }
        public string Courseid { get; set; }
        public Nullable<int> numobjective { get; set; }
        public Nullable<int> numcontent { get; set; }
        public Nullable<int> diff { get; set; }
    }
}
