//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class exerL
    {
        public exerL()
        {
            this.exerDetail = new HashSet<exerDetail>();
        }
    
        public int id { get; set; }
        public string teacherid { get; set; }
        public string name { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<bool> pub { get; set; }
    
        public virtual ICollection<exerDetail> exerDetail { get; set; }
    }
}
