//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_q
    {
        public int idexp { get; set; }
        public byte[] expdoc { get; set; }
        public int courseid { get; set; }
        public byte[] anserdoc { get; set; }
        public int diff { get; set; }
        public string objective { get; set; }
        public int con { get; set; }
        public string exname { get; set; }
        public byte[] attachment { get; set; }
    }
}
