//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class featurehelp
    {
        public int id { get; set; }
        public int type1 { get; set; }
        public int qid { get; set; }
        public string featurestr { get; set; }
        public Nullable<int> con { get; set; }
        public Nullable<int> objective { get; set; }
        public Nullable<int> diff { get; set; }
    }
}
