//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDBservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_tea_course
    {
        public string teacherid { get; set; }
        public string name { get; set; }
        public string pd { get; set; }
        public int couseid { get; set; }
        public int relid { get; set; }
        public string CourseName { get; set; }
        public int numobjective { get; set; }
        public int numcontent { get; set; }
        public int diff { get; set; }
    }
}
