//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Exercise_ERContainer : DbContext
    {
        public Exercise_ERContainer()
            : base("name=Exercise_ERContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudInfo1> StudInfo1Set { get; set; }
        public virtual DbSet<class_student> class_student { get; set; }
        public virtual DbSet<classinfo> classinfo { get; set; }
    }
}
