//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise_plaf.Servicestu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/DB_service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicestu.IService_stu")]
    public interface IService_stu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_stu/Addstu", ReplyAction="http://tempuri.org/IService_stu/AddstuResponse")]
        int Addstu(System.Collections.Generic.List<Exercise_DAL.class_student> c_studl, System.Collections.Generic.List<Exercise_DAL.StudInfo1> studentl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_stu/Addstu", ReplyAction="http://tempuri.org/IService_stu/AddstuResponse")]
        System.Threading.Tasks.Task<int> AddstuAsync(System.Collections.Generic.List<Exercise_DAL.class_student> c_studl, System.Collections.Generic.List<Exercise_DAL.StudInfo1> studentl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_stu/searchstubyclassid", ReplyAction="http://tempuri.org/IService_stu/searchstubyclassidResponse")]
        System.Collections.Generic.List<Exercise_DAL.Studenttemp> searchstubyclassid(int classid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_stu/searchstubyclassid", ReplyAction="http://tempuri.org/IService_stu/searchstubyclassidResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Exercise_DAL.Studenttemp>> searchstubyclassidAsync(int classid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_stu/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService_stu/GetDataUsingDataContractResponse")]
        Exercise_plaf.Servicestu.CompositeType GetDataUsingDataContract(Exercise_plaf.Servicestu.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_stu/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService_stu/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Exercise_plaf.Servicestu.CompositeType> GetDataUsingDataContractAsync(Exercise_plaf.Servicestu.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_stuChannel : Exercise_plaf.Servicestu.IService_stu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_stuClient : System.ServiceModel.ClientBase<Exercise_plaf.Servicestu.IService_stu>, Exercise_plaf.Servicestu.IService_stu {
        
        public Service_stuClient() {
        }
        
        public Service_stuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_stuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_stuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_stuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Addstu(System.Collections.Generic.List<Exercise_DAL.class_student> c_studl, System.Collections.Generic.List<Exercise_DAL.StudInfo1> studentl) {
            return base.Channel.Addstu(c_studl, studentl);
        }
        
        public System.Threading.Tasks.Task<int> AddstuAsync(System.Collections.Generic.List<Exercise_DAL.class_student> c_studl, System.Collections.Generic.List<Exercise_DAL.StudInfo1> studentl) {
            return base.Channel.AddstuAsync(c_studl, studentl);
        }
        
        public System.Collections.Generic.List<Exercise_DAL.Studenttemp> searchstubyclassid(int classid) {
            return base.Channel.searchstubyclassid(classid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Exercise_DAL.Studenttemp>> searchstubyclassidAsync(int classid) {
            return base.Channel.searchstubyclassidAsync(classid);
        }
        
        public Exercise_plaf.Servicestu.CompositeType GetDataUsingDataContract(Exercise_plaf.Servicestu.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Exercise_plaf.Servicestu.CompositeType> GetDataUsingDataContractAsync(Exercise_plaf.Servicestu.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
